# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  
  lane :publish do
    certificates
    archive
    upload_to_internal_store
  end
  
  private_lane :archive do
    gym(scheme: "MatrixScanSettingsSample",
        configuration: "Release",
        export_method: "enterprise",
        output_directory: "build/")
  end
  
  private_lane :upload_to_internal_store do |options|
    version = get_version_number(xcodeproj: "MatrixScanSettingsSample.xcodeproj")
    sh "./upload_ios_app_to_s3.sh ../build/MatrixScanSettingsSample.ipa ../MatrixScanSettingsSample/Assets.xcassets/AppIcon.appiconset/icon-1024.png MatrixScanSettingsSample #{version} com.scandit.MatrixScanSettingsSample"
  end
  
  private_lane :certificates do
    match(app_identifier: "*",
          readonly: true,
          type: "enterprise",
          git_branch: "enterprise")
  end
end